services:
  nginx:
    image: nginx:alpine
    container_name: digestgenie-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - n8n
    networks:
      - digestgenie-network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digestgenie-web
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - digestgenie-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: digestgenie-postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - digestgenie-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: digestgenie-redis
    networks:
      - digestgenie-network
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: digestgenie-n8n
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - digestgenie-network
    restart: unless-stopped

volumes:
  postgres_data:
  n8n_data:

networks:
  digestgenie-network:
    driver: bridge
