version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digestgenie-web-local
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:digestgenie2024@postgres:5432/digestgenie_dev
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=digestgenie-local-secret-key-2024
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
    networks:
      - digestgenie-local

  postgres:
    image: postgres:15-alpine
    container_name: digestgenie-postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: digestgenie2024
      POSTGRES_DB: digestgenie_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - digestgenie-local

  redis:
    image: redis:7-alpine
    container_name: digestgenie-redis-local
    ports:
      - "6379:6379"
    networks:
      - digestgenie-local

  n8n:
    image: n8nio/n8n:latest
    container_name: digestgenie-n8n-local
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=digestgenie-n8n-local-key
    volumes:
      - n8n_data_local:/home/node/.n8n
    networks:
      - digestgenie-local

volumes:
  postgres_data_local:
  n8n_data_local:

networks:
  digestgenie-local:
    driver: bridge
